/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type LutCreated = {
  wrapper: Address;
  lutAddress: Address;
  authority: Address;
  slot: bigint;
};

export type LutCreatedArgs = {
  wrapper: Address;
  lutAddress: Address;
  authority: Address;
  slot: number | bigint;
};

export function getLutCreatedEncoder(): FixedSizeEncoder<LutCreatedArgs> {
  return getStructEncoder([
    ["wrapper", getAddressEncoder()],
    ["lutAddress", getAddressEncoder()],
    ["authority", getAddressEncoder()],
    ["slot", getU64Encoder()],
  ]);
}

export function getLutCreatedDecoder(): FixedSizeDecoder<LutCreated> {
  return getStructDecoder([
    ["wrapper", getAddressDecoder()],
    ["lutAddress", getAddressDecoder()],
    ["authority", getAddressDecoder()],
    ["slot", getU64Decoder()],
  ]);
}

export function getLutCreatedCodec(): FixedSizeCodec<
  LutCreatedArgs,
  LutCreated
> {
  return combineCodec(getLutCreatedEncoder(), getLutCreatedDecoder());
}
