/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type LutClosed = { wrapper: Address; lutAddress: Address };

export type LutClosedArgs = LutClosed;

export function getLutClosedEncoder(): FixedSizeEncoder<LutClosedArgs> {
  return getStructEncoder([
    ["wrapper", getAddressEncoder()],
    ["lutAddress", getAddressEncoder()],
  ]);
}

export function getLutClosedDecoder(): FixedSizeDecoder<LutClosed> {
  return getStructDecoder([
    ["wrapper", getAddressDecoder()],
    ["lutAddress", getAddressDecoder()],
  ]);
}

export function getLutClosedCodec(): FixedSizeCodec<LutClosedArgs, LutClosed> {
  return combineCodec(getLutClosedEncoder(), getLutClosedDecoder());
}
