/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type LutDeactivated = { wrapper: Address; lutAddress: Address };

export type LutDeactivatedArgs = LutDeactivated;

export function getLutDeactivatedEncoder(): FixedSizeEncoder<LutDeactivatedArgs> {
  return getStructEncoder([
    ["wrapper", getAddressEncoder()],
    ["lutAddress", getAddressEncoder()],
  ]);
}

export function getLutDeactivatedDecoder(): FixedSizeDecoder<LutDeactivated> {
  return getStructDecoder([
    ["wrapper", getAddressDecoder()],
    ["lutAddress", getAddressDecoder()],
  ]);
}

export function getLutDeactivatedCodec(): FixedSizeCodec<
  LutDeactivatedArgs,
  LutDeactivated
> {
  return combineCodec(getLutDeactivatedEncoder(), getLutDeactivatedDecoder());
}
