//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshDeserialize;
use borsh::BorshSerialize;

pub const DEACTIVATE_ADDRESS_LOOKUP_TABLE_DISCRIMINATOR: [u8; 8] =
    [125, 173, 92, 250, 29, 247, 245, 192];

/// Accounts.
#[derive(Debug)]
pub struct DeactivateAddressLookupTable {
    pub signer: solana_pubkey::Pubkey,

    pub system_program: solana_pubkey::Pubkey,

    pub address_lookup_table_program: solana_pubkey::Pubkey,

    pub address_lookup_table: solana_pubkey::Pubkey,

    pub user_address_lookup_table: solana_pubkey::Pubkey,

    pub rent: solana_pubkey::Pubkey,
}

impl DeactivateAddressLookupTable {
    pub fn instruction(&self) -> solana_instruction::Instruction {
        self.instruction_with_remaining_accounts(&[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::vec_init_then_push)]
    pub fn instruction_with_remaining_accounts(
        &self,
        remaining_accounts: &[solana_instruction::AccountMeta],
    ) -> solana_instruction::Instruction {
        let mut accounts = Vec::with_capacity(6 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new(self.signer, true));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.system_program,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.address_lookup_table_program,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.address_lookup_table,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.user_address_lookup_table,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.rent, false,
        ));
        accounts.extend_from_slice(remaining_accounts);
        let data = DeactivateAddressLookupTableInstructionData::new()
            .try_to_vec()
            .unwrap();

        solana_instruction::Instruction {
            program_id: crate::LUTS_ID,
            accounts,
            data,
        }
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct DeactivateAddressLookupTableInstructionData {
    discriminator: [u8; 8],
}

impl DeactivateAddressLookupTableInstructionData {
    pub fn new() -> Self {
        Self {
            discriminator: [125, 173, 92, 250, 29, 247, 245, 192],
        }
    }

    pub fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
        borsh::to_vec(self)
    }
}

impl Default for DeactivateAddressLookupTableInstructionData {
    fn default() -> Self {
        Self::new()
    }
}

/// Instruction builder for `DeactivateAddressLookupTable`.
///
/// ### Accounts:
///
///   0. `[writable, signer]` signer
///   1. `[optional]` system_program (default to `11111111111111111111111111111111`)
///   2. `[optional]` address_lookup_table_program (default to `AddressLookupTab1e1111111111111111111111111`)
///   3. `[writable]` address_lookup_table
///   4. `[writable]` user_address_lookup_table
///   5. `[optional]` rent (default to `SysvarRent111111111111111111111111111111111`)
#[derive(Clone, Debug, Default)]
pub struct DeactivateAddressLookupTableBuilder {
    signer: Option<solana_pubkey::Pubkey>,
    system_program: Option<solana_pubkey::Pubkey>,
    address_lookup_table_program: Option<solana_pubkey::Pubkey>,
    address_lookup_table: Option<solana_pubkey::Pubkey>,
    user_address_lookup_table: Option<solana_pubkey::Pubkey>,
    rent: Option<solana_pubkey::Pubkey>,
    __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl DeactivateAddressLookupTableBuilder {
    pub fn new() -> Self {
        Self::default()
    }
    #[inline(always)]
    pub fn signer(&mut self, signer: solana_pubkey::Pubkey) -> &mut Self {
        self.signer = Some(signer);
        self
    }
    /// `[optional account, default to '11111111111111111111111111111111']`
    #[inline(always)]
    pub fn system_program(&mut self, system_program: solana_pubkey::Pubkey) -> &mut Self {
        self.system_program = Some(system_program);
        self
    }
    /// `[optional account, default to 'AddressLookupTab1e1111111111111111111111111']`
    #[inline(always)]
    pub fn address_lookup_table_program(
        &mut self,
        address_lookup_table_program: solana_pubkey::Pubkey,
    ) -> &mut Self {
        self.address_lookup_table_program = Some(address_lookup_table_program);
        self
    }
    #[inline(always)]
    pub fn address_lookup_table(
        &mut self,
        address_lookup_table: solana_pubkey::Pubkey,
    ) -> &mut Self {
        self.address_lookup_table = Some(address_lookup_table);
        self
    }
    #[inline(always)]
    pub fn user_address_lookup_table(
        &mut self,
        user_address_lookup_table: solana_pubkey::Pubkey,
    ) -> &mut Self {
        self.user_address_lookup_table = Some(user_address_lookup_table);
        self
    }
    /// `[optional account, default to 'SysvarRent111111111111111111111111111111111']`
    #[inline(always)]
    pub fn rent(&mut self, rent: solana_pubkey::Pubkey) -> &mut Self {
        self.rent = Some(rent);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
        self.__remaining_accounts.push(account);
        self
    }
    /// Add additional accounts to the instruction.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[solana_instruction::AccountMeta],
    ) -> &mut Self {
        self.__remaining_accounts.extend_from_slice(accounts);
        self
    }
    #[allow(clippy::clone_on_copy)]
    pub fn instruction(&self) -> solana_instruction::Instruction {
        let accounts = DeactivateAddressLookupTable {
            signer: self.signer.expect("signer is not set"),
            system_program: self
                .system_program
                .unwrap_or(solana_pubkey::pubkey!("11111111111111111111111111111111")),
            address_lookup_table_program: self.address_lookup_table_program.unwrap_or(
                solana_pubkey::pubkey!("AddressLookupTab1e1111111111111111111111111"),
            ),
            address_lookup_table: self
                .address_lookup_table
                .expect("address_lookup_table is not set"),
            user_address_lookup_table: self
                .user_address_lookup_table
                .expect("user_address_lookup_table is not set"),
            rent: self.rent.unwrap_or(solana_pubkey::pubkey!(
                "SysvarRent111111111111111111111111111111111"
            )),
        };

        accounts.instruction_with_remaining_accounts(&self.__remaining_accounts)
    }
}

/// `deactivate_address_lookup_table` CPI accounts.
pub struct DeactivateAddressLookupTableCpiAccounts<'a, 'b> {
    pub signer: &'b solana_account_info::AccountInfo<'a>,

    pub system_program: &'b solana_account_info::AccountInfo<'a>,

    pub address_lookup_table_program: &'b solana_account_info::AccountInfo<'a>,

    pub address_lookup_table: &'b solana_account_info::AccountInfo<'a>,

    pub user_address_lookup_table: &'b solana_account_info::AccountInfo<'a>,

    pub rent: &'b solana_account_info::AccountInfo<'a>,
}

/// `deactivate_address_lookup_table` CPI instruction.
pub struct DeactivateAddressLookupTableCpi<'a, 'b> {
    /// The program to invoke.
    pub __program: &'b solana_account_info::AccountInfo<'a>,

    pub signer: &'b solana_account_info::AccountInfo<'a>,

    pub system_program: &'b solana_account_info::AccountInfo<'a>,

    pub address_lookup_table_program: &'b solana_account_info::AccountInfo<'a>,

    pub address_lookup_table: &'b solana_account_info::AccountInfo<'a>,

    pub user_address_lookup_table: &'b solana_account_info::AccountInfo<'a>,

    pub rent: &'b solana_account_info::AccountInfo<'a>,
}

impl<'a, 'b> DeactivateAddressLookupTableCpi<'a, 'b> {
    pub fn new(
        program: &'b solana_account_info::AccountInfo<'a>,
        accounts: DeactivateAddressLookupTableCpiAccounts<'a, 'b>,
    ) -> Self {
        Self {
            __program: program,
            signer: accounts.signer,
            system_program: accounts.system_program,
            address_lookup_table_program: accounts.address_lookup_table_program,
            address_lookup_table: accounts.address_lookup_table,
            user_address_lookup_table: accounts.user_address_lookup_table,
            rent: accounts.rent,
        }
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], &[])
    }
    #[inline(always)]
    pub fn invoke_with_remaining_accounts(
        &self,
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
    }
    #[inline(always)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed_with_remaining_accounts(
        &self,
        signers_seeds: &[&[&[u8]]],
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        let mut accounts = Vec::with_capacity(6 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new(*self.signer.key, true));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.system_program.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.address_lookup_table_program.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.address_lookup_table.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.user_address_lookup_table.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.rent.key,
            false,
        ));
        remaining_accounts.iter().for_each(|remaining_account| {
            accounts.push(solana_instruction::AccountMeta {
                pubkey: *remaining_account.0.key,
                is_signer: remaining_account.1,
                is_writable: remaining_account.2,
            })
        });
        let data = DeactivateAddressLookupTableInstructionData::new()
            .try_to_vec()
            .unwrap();

        let instruction = solana_instruction::Instruction {
            program_id: crate::LUTS_ID,
            accounts,
            data,
        };
        let mut account_infos = Vec::with_capacity(7 + remaining_accounts.len());
        account_infos.push(self.__program.clone());
        account_infos.push(self.signer.clone());
        account_infos.push(self.system_program.clone());
        account_infos.push(self.address_lookup_table_program.clone());
        account_infos.push(self.address_lookup_table.clone());
        account_infos.push(self.user_address_lookup_table.clone());
        account_infos.push(self.rent.clone());
        remaining_accounts
            .iter()
            .for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

        if signers_seeds.is_empty() {
            solana_cpi::invoke(&instruction, &account_infos)
        } else {
            solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
        }
    }
}

/// Instruction builder for `DeactivateAddressLookupTable` via CPI.
///
/// ### Accounts:
///
///   0. `[writable, signer]` signer
///   1. `[]` system_program
///   2. `[]` address_lookup_table_program
///   3. `[writable]` address_lookup_table
///   4. `[writable]` user_address_lookup_table
///   5. `[]` rent
#[derive(Clone, Debug)]
pub struct DeactivateAddressLookupTableCpiBuilder<'a, 'b> {
    instruction: Box<DeactivateAddressLookupTableCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> DeactivateAddressLookupTableCpiBuilder<'a, 'b> {
    pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
        let instruction = Box::new(DeactivateAddressLookupTableCpiBuilderInstruction {
            __program: program,
            signer: None,
            system_program: None,
            address_lookup_table_program: None,
            address_lookup_table: None,
            user_address_lookup_table: None,
            rent: None,
            __remaining_accounts: Vec::new(),
        });
        Self { instruction }
    }
    #[inline(always)]
    pub fn signer(&mut self, signer: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.signer = Some(signer);
        self
    }
    #[inline(always)]
    pub fn system_program(
        &mut self,
        system_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.system_program = Some(system_program);
        self
    }
    #[inline(always)]
    pub fn address_lookup_table_program(
        &mut self,
        address_lookup_table_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.address_lookup_table_program = Some(address_lookup_table_program);
        self
    }
    #[inline(always)]
    pub fn address_lookup_table(
        &mut self,
        address_lookup_table: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.address_lookup_table = Some(address_lookup_table);
        self
    }
    #[inline(always)]
    pub fn user_address_lookup_table(
        &mut self,
        user_address_lookup_table: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.user_address_lookup_table = Some(user_address_lookup_table);
        self
    }
    #[inline(always)]
    pub fn rent(&mut self, rent: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.rent = Some(rent);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: &'b solana_account_info::AccountInfo<'a>,
        is_writable: bool,
        is_signer: bool,
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .push((account, is_writable, is_signer));
        self
    }
    /// Add additional accounts to the instruction.
    ///
    /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
    /// and a `bool` indicating whether the account is a signer or not.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .extend_from_slice(accounts);
        self
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed(&[])
    }
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        let instruction = DeactivateAddressLookupTableCpi {
            __program: self.instruction.__program,

            signer: self.instruction.signer.expect("signer is not set"),

            system_program: self
                .instruction
                .system_program
                .expect("system_program is not set"),

            address_lookup_table_program: self
                .instruction
                .address_lookup_table_program
                .expect("address_lookup_table_program is not set"),

            address_lookup_table: self
                .instruction
                .address_lookup_table
                .expect("address_lookup_table is not set"),

            user_address_lookup_table: self
                .instruction
                .user_address_lookup_table
                .expect("user_address_lookup_table is not set"),

            rent: self.instruction.rent.expect("rent is not set"),
        };
        instruction.invoke_signed_with_remaining_accounts(
            signers_seeds,
            &self.instruction.__remaining_accounts,
        )
    }
}

#[derive(Clone, Debug)]
struct DeactivateAddressLookupTableCpiBuilderInstruction<'a, 'b> {
    __program: &'b solana_account_info::AccountInfo<'a>,
    signer: Option<&'b solana_account_info::AccountInfo<'a>>,
    system_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    address_lookup_table_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    address_lookup_table: Option<&'b solana_account_info::AccountInfo<'a>>,
    user_address_lookup_table: Option<&'b solana_account_info::AccountInfo<'a>>,
    rent: Option<&'b solana_account_info::AccountInfo<'a>>,
    /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
    __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}
