/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { LUTS_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";

export const CLOSE_ADDRESS_LOOKUP_TABLE_DISCRIMINATOR = new Uint8Array([
  177, 46, 58, 36, 157, 194, 183, 58,
]);

export function getCloseAddressLookupTableDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    CLOSE_ADDRESS_LOOKUP_TABLE_DISCRIMINATOR
  );
}

export type CloseAddressLookupTableInstruction<
  TProgram extends string = typeof LUTS_PROGRAM_ADDRESS,
  TAccountSigner extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | AccountMeta<string> = "11111111111111111111111111111111",
  TAccountAddressLookupTableProgram extends
    | string
    | AccountMeta<string> = "AddressLookupTab1e1111111111111111111111111",
  TAccountAddressLookupTable extends string | AccountMeta<string> = string,
  TAccountUserAddressLookupTable extends string | AccountMeta<string> = string,
  TAccountRent extends
    | string
    | AccountMeta<string> = "SysvarRent111111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = []
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountSigner extends string
        ? WritableSignerAccount<TAccountSigner> &
            AccountSignerMeta<TAccountSigner>
        : TAccountSigner,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      TAccountAddressLookupTableProgram extends string
        ? ReadonlyAccount<TAccountAddressLookupTableProgram>
        : TAccountAddressLookupTableProgram,
      TAccountAddressLookupTable extends string
        ? WritableAccount<TAccountAddressLookupTable>
        : TAccountAddressLookupTable,
      TAccountUserAddressLookupTable extends string
        ? WritableAccount<TAccountUserAddressLookupTable>
        : TAccountUserAddressLookupTable,
      TAccountRent extends string
        ? ReadonlyAccount<TAccountRent>
        : TAccountRent,
      ...TRemainingAccounts
    ]
  >;

export type CloseAddressLookupTableInstructionData = {
  discriminator: ReadonlyUint8Array;
};

export type CloseAddressLookupTableInstructionDataArgs = {};

export function getCloseAddressLookupTableInstructionDataEncoder(): FixedSizeEncoder<CloseAddressLookupTableInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([["discriminator", fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({
      ...value,
      discriminator: CLOSE_ADDRESS_LOOKUP_TABLE_DISCRIMINATOR,
    })
  );
}

export function getCloseAddressLookupTableInstructionDataDecoder(): FixedSizeDecoder<CloseAddressLookupTableInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getCloseAddressLookupTableInstructionDataCodec(): FixedSizeCodec<
  CloseAddressLookupTableInstructionDataArgs,
  CloseAddressLookupTableInstructionData
> {
  return combineCodec(
    getCloseAddressLookupTableInstructionDataEncoder(),
    getCloseAddressLookupTableInstructionDataDecoder()
  );
}

export type CloseAddressLookupTableInput<
  TAccountSigner extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountAddressLookupTableProgram extends string = string,
  TAccountAddressLookupTable extends string = string,
  TAccountUserAddressLookupTable extends string = string,
  TAccountRent extends string = string
> = {
  signer: TransactionSigner<TAccountSigner>;
  systemProgram?: Address<TAccountSystemProgram>;
  addressLookupTableProgram?: Address<TAccountAddressLookupTableProgram>;
  addressLookupTable: Address<TAccountAddressLookupTable>;
  userAddressLookupTable: Address<TAccountUserAddressLookupTable>;
  rent?: Address<TAccountRent>;
};

export function getCloseAddressLookupTableInstruction<
  TAccountSigner extends string,
  TAccountSystemProgram extends string,
  TAccountAddressLookupTableProgram extends string,
  TAccountAddressLookupTable extends string,
  TAccountUserAddressLookupTable extends string,
  TAccountRent extends string,
  TProgramAddress extends Address = typeof LUTS_PROGRAM_ADDRESS
>(
  input: CloseAddressLookupTableInput<
    TAccountSigner,
    TAccountSystemProgram,
    TAccountAddressLookupTableProgram,
    TAccountAddressLookupTable,
    TAccountUserAddressLookupTable,
    TAccountRent
  >,
  config?: { programAddress?: TProgramAddress }
): CloseAddressLookupTableInstruction<
  TProgramAddress,
  TAccountSigner,
  TAccountSystemProgram,
  TAccountAddressLookupTableProgram,
  TAccountAddressLookupTable,
  TAccountUserAddressLookupTable,
  TAccountRent
> {
  // Program address.
  const programAddress = config?.programAddress ?? LUTS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    signer: { value: input.signer ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    addressLookupTableProgram: {
      value: input.addressLookupTableProgram ?? null,
      isWritable: false,
    },
    addressLookupTable: {
      value: input.addressLookupTable ?? null,
      isWritable: true,
    },
    userAddressLookupTable: {
      value: input.userAddressLookupTable ?? null,
      isWritable: true,
    },
    rent: { value: input.rent ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }
  if (!accounts.addressLookupTableProgram.value) {
    accounts.addressLookupTableProgram.value =
      "AddressLookupTab1e1111111111111111111111111" as Address<"AddressLookupTab1e1111111111111111111111111">;
  }
  if (!accounts.rent.value) {
    accounts.rent.value =
      "SysvarRent111111111111111111111111111111111" as Address<"SysvarRent111111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.signer),
      getAccountMeta(accounts.systemProgram),
      getAccountMeta(accounts.addressLookupTableProgram),
      getAccountMeta(accounts.addressLookupTable),
      getAccountMeta(accounts.userAddressLookupTable),
      getAccountMeta(accounts.rent),
    ],
    data: getCloseAddressLookupTableInstructionDataEncoder().encode({}),
    programAddress,
  } as CloseAddressLookupTableInstruction<TProgramAddress, TAccountSigner, TAccountSystemProgram, TAccountAddressLookupTableProgram, TAccountAddressLookupTable, TAccountUserAddressLookupTable, TAccountRent>);
}

export type ParsedCloseAddressLookupTableInstruction<
  TProgram extends string = typeof LUTS_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[]
> = {
  programAddress: Address<TProgram>;
  accounts: {
    signer: TAccountMetas[0];
    systemProgram: TAccountMetas[1];
    addressLookupTableProgram: TAccountMetas[2];
    addressLookupTable: TAccountMetas[3];
    userAddressLookupTable: TAccountMetas[4];
    rent: TAccountMetas[5];
  };
  data: CloseAddressLookupTableInstructionData;
};

export function parseCloseAddressLookupTableInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[]
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedCloseAddressLookupTableInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 6) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      signer: getNextAccount(),
      systemProgram: getNextAccount(),
      addressLookupTableProgram: getNextAccount(),
      addressLookupTable: getNextAccount(),
      userAddressLookupTable: getNextAccount(),
      rent: getNextAccount(),
    },
    data: getCloseAddressLookupTableInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
