/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { LUTS_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";

export const CREATE_ADDRESS_LOOKUP_TABLE_DISCRIMINATOR = new Uint8Array([
  90, 11, 161, 229, 55, 168, 159, 87,
]);

export function getCreateAddressLookupTableDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    CREATE_ADDRESS_LOOKUP_TABLE_DISCRIMINATOR
  );
}

export type CreateAddressLookupTableInstruction<
  TProgram extends string = typeof LUTS_PROGRAM_ADDRESS,
  TAccountSigner extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | AccountMeta<string> = "11111111111111111111111111111111",
  TAccountAddressLookupTableProgram extends
    | string
    | AccountMeta<string> = "AddressLookupTab1e1111111111111111111111111",
  TAccountAddressLookupTable extends string | AccountMeta<string> = string,
  TAccountUserAddressLookupTable extends string | AccountMeta<string> = string,
  TAccountRent extends
    | string
    | AccountMeta<string> = "SysvarRent111111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = []
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountSigner extends string
        ? WritableSignerAccount<TAccountSigner> &
            AccountSignerMeta<TAccountSigner>
        : TAccountSigner,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      TAccountAddressLookupTableProgram extends string
        ? ReadonlyAccount<TAccountAddressLookupTableProgram>
        : TAccountAddressLookupTableProgram,
      TAccountAddressLookupTable extends string
        ? WritableAccount<TAccountAddressLookupTable>
        : TAccountAddressLookupTable,
      TAccountUserAddressLookupTable extends string
        ? WritableAccount<TAccountUserAddressLookupTable>
        : TAccountUserAddressLookupTable,
      TAccountRent extends string
        ? ReadonlyAccount<TAccountRent>
        : TAccountRent,
      ...TRemainingAccounts
    ]
  >;

export type CreateAddressLookupTableInstructionData = {
  discriminator: ReadonlyUint8Array;
  recentSlot: bigint;
  id: bigint;
};

export type CreateAddressLookupTableInstructionDataArgs = {
  recentSlot: number | bigint;
  id: number | bigint;
};

export function getCreateAddressLookupTableInstructionDataEncoder(): FixedSizeEncoder<CreateAddressLookupTableInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["recentSlot", getU64Encoder()],
      ["id", getU64Encoder()],
    ]),
    (value) => ({
      ...value,
      discriminator: CREATE_ADDRESS_LOOKUP_TABLE_DISCRIMINATOR,
    })
  );
}

export function getCreateAddressLookupTableInstructionDataDecoder(): FixedSizeDecoder<CreateAddressLookupTableInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["recentSlot", getU64Decoder()],
    ["id", getU64Decoder()],
  ]);
}

export function getCreateAddressLookupTableInstructionDataCodec(): FixedSizeCodec<
  CreateAddressLookupTableInstructionDataArgs,
  CreateAddressLookupTableInstructionData
> {
  return combineCodec(
    getCreateAddressLookupTableInstructionDataEncoder(),
    getCreateAddressLookupTableInstructionDataDecoder()
  );
}

export type CreateAddressLookupTableInput<
  TAccountSigner extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountAddressLookupTableProgram extends string = string,
  TAccountAddressLookupTable extends string = string,
  TAccountUserAddressLookupTable extends string = string,
  TAccountRent extends string = string
> = {
  signer: TransactionSigner<TAccountSigner>;
  systemProgram?: Address<TAccountSystemProgram>;
  addressLookupTableProgram?: Address<TAccountAddressLookupTableProgram>;
  addressLookupTable: Address<TAccountAddressLookupTable>;
  userAddressLookupTable: Address<TAccountUserAddressLookupTable>;
  rent?: Address<TAccountRent>;
  recentSlot: CreateAddressLookupTableInstructionDataArgs["recentSlot"];
  id: CreateAddressLookupTableInstructionDataArgs["id"];
};

export function getCreateAddressLookupTableInstruction<
  TAccountSigner extends string,
  TAccountSystemProgram extends string,
  TAccountAddressLookupTableProgram extends string,
  TAccountAddressLookupTable extends string,
  TAccountUserAddressLookupTable extends string,
  TAccountRent extends string,
  TProgramAddress extends Address = typeof LUTS_PROGRAM_ADDRESS
>(
  input: CreateAddressLookupTableInput<
    TAccountSigner,
    TAccountSystemProgram,
    TAccountAddressLookupTableProgram,
    TAccountAddressLookupTable,
    TAccountUserAddressLookupTable,
    TAccountRent
  >,
  config?: { programAddress?: TProgramAddress }
): CreateAddressLookupTableInstruction<
  TProgramAddress,
  TAccountSigner,
  TAccountSystemProgram,
  TAccountAddressLookupTableProgram,
  TAccountAddressLookupTable,
  TAccountUserAddressLookupTable,
  TAccountRent
> {
  // Program address.
  const programAddress = config?.programAddress ?? LUTS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    signer: { value: input.signer ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    addressLookupTableProgram: {
      value: input.addressLookupTableProgram ?? null,
      isWritable: false,
    },
    addressLookupTable: {
      value: input.addressLookupTable ?? null,
      isWritable: true,
    },
    userAddressLookupTable: {
      value: input.userAddressLookupTable ?? null,
      isWritable: true,
    },
    rent: { value: input.rent ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }
  if (!accounts.addressLookupTableProgram.value) {
    accounts.addressLookupTableProgram.value =
      "AddressLookupTab1e1111111111111111111111111" as Address<"AddressLookupTab1e1111111111111111111111111">;
  }
  if (!accounts.rent.value) {
    accounts.rent.value =
      "SysvarRent111111111111111111111111111111111" as Address<"SysvarRent111111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.signer),
      getAccountMeta(accounts.systemProgram),
      getAccountMeta(accounts.addressLookupTableProgram),
      getAccountMeta(accounts.addressLookupTable),
      getAccountMeta(accounts.userAddressLookupTable),
      getAccountMeta(accounts.rent),
    ],
    data: getCreateAddressLookupTableInstructionDataEncoder().encode(
      args as CreateAddressLookupTableInstructionDataArgs
    ),
    programAddress,
  } as CreateAddressLookupTableInstruction<TProgramAddress, TAccountSigner, TAccountSystemProgram, TAccountAddressLookupTableProgram, TAccountAddressLookupTable, TAccountUserAddressLookupTable, TAccountRent>);
}

export type ParsedCreateAddressLookupTableInstruction<
  TProgram extends string = typeof LUTS_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[]
> = {
  programAddress: Address<TProgram>;
  accounts: {
    signer: TAccountMetas[0];
    systemProgram: TAccountMetas[1];
    addressLookupTableProgram: TAccountMetas[2];
    addressLookupTable: TAccountMetas[3];
    userAddressLookupTable: TAccountMetas[4];
    rent: TAccountMetas[5];
  };
  data: CreateAddressLookupTableInstructionData;
};

export function parseCreateAddressLookupTableInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[]
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedCreateAddressLookupTableInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 6) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      signer: getNextAccount(),
      systemProgram: getNextAccount(),
      addressLookupTableProgram: getNextAccount(),
      addressLookupTable: getNextAccount(),
      userAddressLookupTable: getNextAccount(),
      rent: getNextAccount(),
    },
    data: getCreateAddressLookupTableInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
