//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use solana_pubkey::{pubkey, Pubkey};

/// `luts` program ID.
pub const LUTS_ID: Pubkey = pubkey!("846qK5Drj9NEn2P4AvXCKxoVnyYQYGzMu2W7gyvoYjHT");
