/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  containsBytes,
  fixEncoderSize,
  getBytesEncoder,
  type Address,
  type ReadonlyUint8Array,
} from "@solana/kit";
import {
  type ParsedCloseAddressLookupTableInstruction,
  type ParsedCreateAddressLookupTableInstruction,
  type ParsedDeactivateAddressLookupTableInstruction,
  type ParsedExtendAddressLookupTableInstruction,
} from "../instructions";

export const LUTS_PROGRAM_ADDRESS =
  "846qK5Drj9NEn2P4AvXCKxoVnyYQYGzMu2W7gyvoYjHT" as Address<"846qK5Drj9NEn2P4AvXCKxoVnyYQYGzMu2W7gyvoYjHT">;

export enum LutsAccount {
  UserAddressLookupTable,
}

export function identifyLutsAccount(
  account: { data: ReadonlyUint8Array } | ReadonlyUint8Array
): LutsAccount {
  const data = "data" in account ? account.data : account;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([28, 183, 129, 166, 216, 32, 90, 100])
      ),
      0
    )
  ) {
    return LutsAccount.UserAddressLookupTable;
  }
  throw new Error(
    "The provided account could not be identified as a luts account."
  );
}

export enum LutsInstruction {
  CloseAddressLookupTable,
  CreateAddressLookupTable,
  DeactivateAddressLookupTable,
  ExtendAddressLookupTable,
}

export function identifyLutsInstruction(
  instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array
): LutsInstruction {
  const data = "data" in instruction ? instruction.data : instruction;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([177, 46, 58, 36, 157, 194, 183, 58])
      ),
      0
    )
  ) {
    return LutsInstruction.CloseAddressLookupTable;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([90, 11, 161, 229, 55, 168, 159, 87])
      ),
      0
    )
  ) {
    return LutsInstruction.CreateAddressLookupTable;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([125, 173, 92, 250, 29, 247, 245, 192])
      ),
      0
    )
  ) {
    return LutsInstruction.DeactivateAddressLookupTable;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([251, 61, 236, 47, 121, 159, 253, 159])
      ),
      0
    )
  ) {
    return LutsInstruction.ExtendAddressLookupTable;
  }
  throw new Error(
    "The provided instruction could not be identified as a luts instruction."
  );
}

export type ParsedLutsInstruction<
  TProgram extends string = "846qK5Drj9NEn2P4AvXCKxoVnyYQYGzMu2W7gyvoYjHT"
> =
  | ({
      instructionType: LutsInstruction.CloseAddressLookupTable;
    } & ParsedCloseAddressLookupTableInstruction<TProgram>)
  | ({
      instructionType: LutsInstruction.CreateAddressLookupTable;
    } & ParsedCreateAddressLookupTableInstruction<TProgram>)
  | ({
      instructionType: LutsInstruction.DeactivateAddressLookupTable;
    } & ParsedDeactivateAddressLookupTableInstruction<TProgram>)
  | ({
      instructionType: LutsInstruction.ExtendAddressLookupTable;
    } & ParsedExtendAddressLookupTableInstruction<TProgram>);
