/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";

export const USER_ADDRESS_LOOKUP_TABLE_DISCRIMINATOR = new Uint8Array([
  28, 183, 129, 166, 216, 32, 90, 100,
]);

export function getUserAddressLookupTableDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    USER_ADDRESS_LOOKUP_TABLE_DISCRIMINATOR
  );
}

export type UserAddressLookupTable = {
  discriminator: ReadonlyUint8Array;
  bump: number;
  signer: Address;
  size: bigint;
  id: bigint;
  addressLookupTable: Address;
  lastUpdatedSlot: bigint;
};

export type UserAddressLookupTableArgs = {
  bump: number;
  signer: Address;
  size: number | bigint;
  id: number | bigint;
  addressLookupTable: Address;
  lastUpdatedSlot: number | bigint;
};

/** Gets the encoder for {@link UserAddressLookupTableArgs} account data. */
export function getUserAddressLookupTableEncoder(): FixedSizeEncoder<UserAddressLookupTableArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["bump", getU8Encoder()],
      ["signer", getAddressEncoder()],
      ["size", getU64Encoder()],
      ["id", getU64Encoder()],
      ["addressLookupTable", getAddressEncoder()],
      ["lastUpdatedSlot", getU64Encoder()],
    ]),
    (value) => ({
      ...value,
      discriminator: USER_ADDRESS_LOOKUP_TABLE_DISCRIMINATOR,
    })
  );
}

/** Gets the decoder for {@link UserAddressLookupTable} account data. */
export function getUserAddressLookupTableDecoder(): FixedSizeDecoder<UserAddressLookupTable> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["bump", getU8Decoder()],
    ["signer", getAddressDecoder()],
    ["size", getU64Decoder()],
    ["id", getU64Decoder()],
    ["addressLookupTable", getAddressDecoder()],
    ["lastUpdatedSlot", getU64Decoder()],
  ]);
}

/** Gets the codec for {@link UserAddressLookupTable} account data. */
export function getUserAddressLookupTableCodec(): FixedSizeCodec<
  UserAddressLookupTableArgs,
  UserAddressLookupTable
> {
  return combineCodec(
    getUserAddressLookupTableEncoder(),
    getUserAddressLookupTableDecoder()
  );
}

export function decodeUserAddressLookupTable<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>
): Account<UserAddressLookupTable, TAddress>;
export function decodeUserAddressLookupTable<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>
): MaybeAccount<UserAddressLookupTable, TAddress>;
export function decodeUserAddressLookupTable<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>
):
  | Account<UserAddressLookupTable, TAddress>
  | MaybeAccount<UserAddressLookupTable, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getUserAddressLookupTableDecoder()
  );
}

export async function fetchUserAddressLookupTable<
  TAddress extends string = string
>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<Account<UserAddressLookupTable, TAddress>> {
  const maybeAccount = await fetchMaybeUserAddressLookupTable(
    rpc,
    address,
    config
  );
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeUserAddressLookupTable<
  TAddress extends string = string
>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<MaybeAccount<UserAddressLookupTable, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeUserAddressLookupTable(maybeAccount);
}

export async function fetchAllUserAddressLookupTable(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<Account<UserAddressLookupTable>[]> {
  const maybeAccounts = await fetchAllMaybeUserAddressLookupTable(
    rpc,
    addresses,
    config
  );
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeUserAddressLookupTable(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<MaybeAccount<UserAddressLookupTable>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) =>
    decodeUserAddressLookupTable(maybeAccount)
  );
}

export function getUserAddressLookupTableSize(): number {
  return 97;
}
